/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prepaidforge.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SkuRequest
 */
public class SkuRequestTest {
    private final SkuRequest model = new SkuRequest();

    /**
     * Model tests for SkuRequest
     */
    @Test
    public void testSkuRequest() {
        // TODO: test SkuRequest
    }

    /**
     * Test the property 'stockId'
     */
    @Test
    public void stockIdTest() {
        // TODO: test stockId
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'codeType'
     */
    @Test
    public void codeTypeTest() {
        // TODO: test codeType
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'customOrderReference'
     */
    @Test
    public void customOrderReferenceTest() {
        // TODO: test customOrderReference
    }

    /**
     * Test the property 'quantityHandled'
     */
    @Test
    public void quantityHandledTest() {
        // TODO: test quantityHandled
    }

    /**
     * Test the property 'quantityNeeded'
     */
    @Test
    public void quantityNeededTest() {
        // TODO: test quantityNeeded
    }

    /**
     * Test the property 'requestHandled'
     */
    @Test
    public void requestHandledTest() {
        // TODO: test requestHandled
    }

}
