/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prepaidforge.client.api;

import com.prepaidforge.client.ApiCallback;
import com.prepaidforge.client.ApiClient;
import com.prepaidforge.client.ApiException;
import com.prepaidforge.client.ApiResponse;
import com.prepaidforge.client.Configuration;
import com.prepaidforge.client.Pair;
import com.prepaidforge.client.ProgressRequestBody;
import com.prepaidforge.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.prepaidforge.client.model.ApiSignInResponse;
import com.prepaidforge.client.model.MerchantSignInRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UserApi {
    private ApiClient localVarApiClient;

    public UserApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UserApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for signInWithApi
     * @param merchantSignInRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> default response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call signInWithApiCall(MerchantSignInRequest merchantSignInRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = merchantSignInRequest;

        // create path and map variables
        String localVarPath = "/1.0/signInWithApi";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call signInWithApiValidateBeforeCall(MerchantSignInRequest merchantSignInRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = signInWithApiCall(merchantSignInRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Sign in link for api users
     * @param merchantSignInRequest  (optional)
     * @return ApiSignInResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> default response </td><td>  -  </td></tr>
     </table>
     */
    public ApiSignInResponse signInWithApi(MerchantSignInRequest merchantSignInRequest) throws ApiException {
        ApiResponse<ApiSignInResponse> localVarResp = signInWithApiWithHttpInfo(merchantSignInRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Sign in link for api users
     * @param merchantSignInRequest  (optional)
     * @return ApiResponse&lt;ApiSignInResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> default response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiSignInResponse> signInWithApiWithHttpInfo(MerchantSignInRequest merchantSignInRequest) throws ApiException {
        okhttp3.Call localVarCall = signInWithApiValidateBeforeCall(merchantSignInRequest, null);
        Type localVarReturnType = new TypeToken<ApiSignInResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Sign in link for api users
     * @param merchantSignInRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> default response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call signInWithApiAsync(MerchantSignInRequest merchantSignInRequest, final ApiCallback<ApiSignInResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = signInWithApiValidateBeforeCall(merchantSignInRequest, _callback);
        Type localVarReturnType = new TypeToken<ApiSignInResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
