/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiSignInResponse
 */
public class ApiSignInResponseTest {
    private final ApiSignInResponse model = new ApiSignInResponse();

    /**
     * Model tests for ApiSignInResponse
     */
    @Test
    public void testApiSignInResponse() {
        // TODO: test ApiSignInResponse
    }

    /**
     * Test the property 'apiToken'
     */
    @Test
    public void apiTokenTest() {
        // TODO: test apiToken
    }

    /**
     * Test the property 'tokenValidUntil'
     */
    @Test
    public void tokenValidUntilTest() {
        // TODO: test tokenValidUntil
    }

}
