/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Money
 */
public class MoneyTest {
    private final Money model = new Money();

    /**
     * Model tests for Money
     */
    @Test
    public void testMoney() {
        // TODO: test Money
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'formattedString'
     */
    @Test
    public void formattedStringTest() {
        // TODO: test formattedString
    }

    /**
     * Test the property 'roundedFormattedString'
     */
    @Test
    public void roundedFormattedStringTest() {
        // TODO: test roundedFormattedString
    }

    /**
     * Test the property 'csvamount'
     */
    @Test
    public void csvamountTest() {
        // TODO: test csvamount
    }

}
