/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Brand;
import org.openapitools.client.model.Category;
import org.openapitools.client.model.Country;
import org.openapitools.client.model.Language;
import org.openapitools.client.model.Money;
import org.openapitools.client.model.Platform;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Product
 */
public class ProductTest {
    private final Product model = new Product();

    /**
     * Model tests for Product
     */
    @Test
    public void testProduct() {
        // TODO: test Product
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateUpdated'
     */
    @Test
    public void dateUpdatedTest() {
        // TODO: test dateUpdated
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'gtin'
     */
    @Test
    public void gtinTest() {
        // TODO: test gtin
    }

    /**
     * Test the property 'ean'
     */
    @Test
    public void eanTest() {
        // TODO: test ean
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'faceValue'
     */
    @Test
    public void faceValueTest() {
        // TODO: test faceValue
    }

    /**
     * Test the property 'defaultPrice'
     */
    @Test
    public void defaultPriceTest() {
        // TODO: test defaultPrice
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'isCurrencyProduct'
     */
    @Test
    public void isCurrencyProductTest() {
        // TODO: test isCurrencyProduct
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'languages'
     */
    @Test
    public void languagesTest() {
        // TODO: test languages
    }

    /**
     * Test the property 'countries'
     */
    @Test
    public void countriesTest() {
        // TODO: test countries
    }

    /**
     * Test the property 'platforms'
     */
    @Test
    public void platformsTest() {
        // TODO: test platforms
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'productType'
     */
    @Test
    public void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'vatProduct'
     */
    @Test
    public void vatProductTest() {
        // TODO: test vatProduct
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'productDifferenceHash'
     */
    @Test
    public void productDifferenceHashTest() {
        // TODO: test productDifferenceHash
    }

}
