/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prepaidforge.client.api;

import com.prepaidforge.client.ApiException;
import com.prepaidforge.client.Configuration;
import com.prepaidforge.client.model.ApiSignInResponse;
import com.prepaidforge.client.model.MerchantSignInRequest;
import org.junit.Test;
import org.junit.Assert;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * 
     *
     * Sign in link for api users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(timeout = 100000)
    public void signInWithApiTest() throws ApiException {
        Configuration.getDefaultApiClient().setBasePath("http://localhost:8080/api-1.0-SNAPSHOT/v1");
        MerchantSignInRequest merchantSignInRequest = new MerchantSignInRequest().email("USERNAME").password("PASS");
        ApiSignInResponse response = new UserApi().signInWithApi(merchantSignInRequest);
        String apiToken = response.getApiToken();
        String s = response.getTokenValidUntil();

        Assert.assertNotNull(apiToken);
        Assert.assertNotNull(s);
    }
    
}
