/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prepaidforge.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiSignInResponse
 */

public class ApiSignInResponse {
  public static final String SERIALIZED_NAME_API_TOKEN = "apiToken";
  @SerializedName(SERIALIZED_NAME_API_TOKEN)
  private String apiToken;

  public static final String SERIALIZED_NAME_TOKEN_VALID_UNTIL = "tokenValidUntil";
  @SerializedName(SERIALIZED_NAME_TOKEN_VALID_UNTIL)
  private String tokenValidUntil;

  public ApiSignInResponse apiToken(String apiToken) {
    this.apiToken = apiToken;
    return this;
  }

   /**
   * Get apiToken
   * @return apiToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public String getApiToken() {
    return apiToken;
  }

  public void setApiToken(String apiToken) {
    this.apiToken = apiToken;
  }

  public ApiSignInResponse tokenValidUntil(String tokenValidUntil) {
    this.tokenValidUntil = tokenValidUntil;
    return this;
  }

   /**
   * Get tokenValidUntil
   * @return tokenValidUntil
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public String getTokenValidUntil() {
    return tokenValidUntil;
  }

  public void setTokenValidUntil(String tokenValidUntil) {
    this.tokenValidUntil = tokenValidUntil;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSignInResponse apiSignInResponse = (ApiSignInResponse) o;
    return Objects.equals(this.apiToken, apiSignInResponse.apiToken) &&
        Objects.equals(this.tokenValidUntil, apiSignInResponse.tokenValidUntil);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiToken, tokenValidUntil);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSignInResponse {\n");
    sb.append("    apiToken: ").append(toIndentedString(apiToken)).append("\n");
    sb.append("    tokenValidUntil: ").append(toIndentedString(tokenValidUntil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

