/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prepaidforge.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * SkuRequest
 */

public class SkuRequest {
  public static final String SERIALIZED_NAME_STOCK_ID = "stockId";
  @SerializedName(SERIALIZED_NAME_STOCK_ID)
  private Long stockId;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  /**
   * Gets or Sets codeType
   */
  @JsonAdapter(CodeTypeEnum.Adapter.class)
  public enum CodeTypeEnum {
    TEXT("TEXT"),
    
    SCAN("SCAN"),
    
    FULLSCAN("FULLSCAN"),
    
    OCR("OCR"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    CodeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodeTypeEnum fromValue(String value) {
      for (CodeTypeEnum b : CodeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CodeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CodeTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CODE_TYPE = "codeType";
  @SerializedName(SERIALIZED_NAME_CODE_TYPE)
  private CodeTypeEnum codeType;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private BigDecimal quantity;

  public static final String SERIALIZED_NAME_CUSTOM_ORDER_REFERENCE = "customOrderReference";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ORDER_REFERENCE)
  private String customOrderReference;

  public static final String SERIALIZED_NAME_QUANTITY_HANDLED = "quantityHandled";
  @SerializedName(SERIALIZED_NAME_QUANTITY_HANDLED)
  private Integer quantityHandled;

  public static final String SERIALIZED_NAME_QUANTITY_NEEDED = "quantityNeeded";
  @SerializedName(SERIALIZED_NAME_QUANTITY_NEEDED)
  private BigDecimal quantityNeeded;

  public static final String SERIALIZED_NAME_REQUEST_HANDLED = "requestHandled";
  @SerializedName(SERIALIZED_NAME_REQUEST_HANDLED)
  private Boolean requestHandled;

  public SkuRequest stockId(Long stockId) {
    this.stockId = stockId;
    return this;
  }

   /**
   * Get stockId
   * @return stockId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public Long getStockId() {
    return stockId;
  }

  public void setStockId(Long stockId) {
    this.stockId = stockId;
  }

  public SkuRequest sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public SkuRequest price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public SkuRequest codeType(CodeTypeEnum codeType) {
    this.codeType = codeType;
    return this;
  }

   /**
   * Get codeType
   * @return codeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public CodeTypeEnum getCodeType() {
    return codeType;
  }

  public void setCodeType(CodeTypeEnum codeType) {
    this.codeType = codeType;
  }

  public SkuRequest quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public SkuRequest customOrderReference(String customOrderReference) {
    this.customOrderReference = customOrderReference;
    return this;
  }

   /**
   * Get customOrderReference
   * @return customOrderReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public String getCustomOrderReference() {
    return customOrderReference;
  }

  public void setCustomOrderReference(String customOrderReference) {
    this.customOrderReference = customOrderReference;
  }

  public SkuRequest quantityHandled(Integer quantityHandled) {
    this.quantityHandled = quantityHandled;
    return this;
  }

   /**
   * Get quantityHandled
   * @return quantityHandled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public Integer getQuantityHandled() {
    return quantityHandled;
  }

  public void setQuantityHandled(Integer quantityHandled) {
    this.quantityHandled = quantityHandled;
  }

  public SkuRequest quantityNeeded(BigDecimal quantityNeeded) {
    this.quantityNeeded = quantityNeeded;
    return this;
  }

   /**
   * Get quantityNeeded
   * @return quantityNeeded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public BigDecimal getQuantityNeeded() {
    return quantityNeeded;
  }

  public void setQuantityNeeded(BigDecimal quantityNeeded) {
    this.quantityNeeded = quantityNeeded;
  }

  public SkuRequest requestHandled(Boolean requestHandled) {
    this.requestHandled = requestHandled;
    return this;
  }

   /**
   * Get requestHandled
   * @return requestHandled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  public Boolean getRequestHandled() {
    return requestHandled;
  }

  public void setRequestHandled(Boolean requestHandled) {
    this.requestHandled = requestHandled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkuRequest skuRequest = (SkuRequest) o;
    return Objects.equals(this.stockId, skuRequest.stockId) &&
        Objects.equals(this.sku, skuRequest.sku) &&
        Objects.equals(this.price, skuRequest.price) &&
        Objects.equals(this.codeType, skuRequest.codeType) &&
        Objects.equals(this.quantity, skuRequest.quantity) &&
        Objects.equals(this.customOrderReference, skuRequest.customOrderReference) &&
        Objects.equals(this.quantityHandled, skuRequest.quantityHandled) &&
        Objects.equals(this.quantityNeeded, skuRequest.quantityNeeded) &&
        Objects.equals(this.requestHandled, skuRequest.requestHandled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stockId, sku, price, codeType, quantity, customOrderReference, quantityHandled, quantityNeeded, requestHandled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkuRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    customOrderReference: ").append(toIndentedString(customOrderReference)).append("\n");
    sb.append("    quantityHandled: ").append(toIndentedString(quantityHandled)).append("\n");
    sb.append("    quantityNeeded: ").append(toIndentedString(quantityNeeded)).append("\n");
    sb.append("    requestHandled: ").append(toIndentedString(requestHandled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

