/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Money
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-11T15:19:56.881Z[GMT]")
public class Money {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;

  /**
   * Gets or Sets currency
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    EUR("EUR"),
    
    USD("USD"),
    
    GBP("GBP"),
    
    CHF("CHF"),
    
    DKK("DKK"),
    
    NOK("NOK"),
    
    PLN("PLN"),
    
    SEK("SEK"),
    
    RUB("RUB"),
    
    AUD("AUD"),
    
    CAD("CAD");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private CurrencyEnum currency;

  public static final String SERIALIZED_NAME_FORMATTED_STRING = "formattedString";
  @SerializedName(SERIALIZED_NAME_FORMATTED_STRING)
  private String formattedString;

  public static final String SERIALIZED_NAME_ROUNDED_FORMATTED_STRING = "roundedFormattedString";
  @SerializedName(SERIALIZED_NAME_ROUNDED_FORMATTED_STRING)
  private String roundedFormattedString;

  public static final String SERIALIZED_NAME_CSVAMOUNT = "csvamount";
  @SerializedName(SERIALIZED_NAME_CSVAMOUNT)
  private String csvamount;

  public Money amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public Money currency(CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyEnum currency) {
    this.currency = currency;
  }

  public Money formattedString(String formattedString) {
    this.formattedString = formattedString;
    return this;
  }

   /**
   * Get formattedString
   * @return formattedString
  **/
  @ApiModelProperty(value = "")
  public String getFormattedString() {
    return formattedString;
  }

  public void setFormattedString(String formattedString) {
    this.formattedString = formattedString;
  }

  public Money roundedFormattedString(String roundedFormattedString) {
    this.roundedFormattedString = roundedFormattedString;
    return this;
  }

   /**
   * Get roundedFormattedString
   * @return roundedFormattedString
  **/
  @ApiModelProperty(value = "")
  public String getRoundedFormattedString() {
    return roundedFormattedString;
  }

  public void setRoundedFormattedString(String roundedFormattedString) {
    this.roundedFormattedString = roundedFormattedString;
  }

  public Money csvamount(String csvamount) {
    this.csvamount = csvamount;
    return this;
  }

   /**
   * Get csvamount
   * @return csvamount
  **/
  @ApiModelProperty(value = "")
  public String getCsvamount() {
    return csvamount;
  }

  public void setCsvamount(String csvamount) {
    this.csvamount = csvamount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Money money = (Money) o;
    return Objects.equals(this.amount, money.amount) &&
        Objects.equals(this.currency, money.currency) &&
        Objects.equals(this.formattedString, money.formattedString) &&
        Objects.equals(this.roundedFormattedString, money.roundedFormattedString) &&
        Objects.equals(this.csvamount, money.csvamount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currency, formattedString, roundedFormattedString, csvamount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Money {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    formattedString: ").append(toIndentedString(formattedString)).append("\n");
    sb.append("    roundedFormattedString: ").append(toIndentedString(roundedFormattedString)).append("\n");
    sb.append("    csvamount: ").append(toIndentedString(csvamount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

