/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.*;

import org.openapitools.client.ApiException;
import org.openapitools.client.Configuration;
import org.openapitools.client.model.CodeDeliveryPojo;
import org.openapitools.client.model.MerchantSignInRequest;
import org.openapitools.client.model.SkuRequest;
import org.openapitools.client.model.SkuRequest.CodeTypeEnum;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersCodesApi
 */
public class OrdersCodesApiTest {

    private final OrdersCodesApi api = new OrdersCodesApi();

    
    @Before
    public void init() throws ApiException {
        MerchantSignInRequest merchantSignInRequest = new MerchantSignInRequest()
        .email("USERNAME")
        .password("PASS");
ApiSignInResponse response = new UserApi().signInWithApi(merchantSignInRequest);
String apiToken = response.getApiToken();
        Configuration
        .getDefaultApiClient()
        .setReadTimeout(10000000)
        .setBasePath("http://localhost:8080/api-1.0-SNAPSHOT/v1")
        .setApiKey(apiToken);
    }

    /**
     * 
     *
     * creates order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(timeout = 1000000000)
    public void createSingleOrderTest() throws ApiException {
        SkuRequest skuRequest = new SkuRequest();
        skuRequest.codeType(CodeTypeEnum.TEXT)
            .sku("iTunes-10-USD")
            .customOrderReference("customOrderReference1234aw123iuh1")
            .quantity(new BigDecimal("1"))
            .price(new BigDecimal("8.6726"));
        CodeDeliveryPojo response = api.createSingleOrder(skuRequest);
        System.out.println(response);
    }
    
    /**
     * 
     *
     * Retrieve code using custom order reference
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResponseOfSingleCodeRequestTest() throws ApiException {
        SkuRequest skuRequest = new SkuRequest();
        skuRequest.customOrderReference("customOrderReference1234aw123iuh1");
        CodeDeliveryPojo response = api.getResponseOfSingleCodeRequest(skuRequest);

        // TODO: test validations
    }
    
}
