/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.Configuration;
import org.openapitools.client.model.ApiSignInResponse;
import org.openapitools.client.model.MerchantSignInRequest;
import org.openapitools.client.model.Product;
import org.openapitools.client.model.SimpleStockPojo;
import org.openapitools.client.model.StockRequest;
import org.openapitools.client.model.StockRequest.TypesEnum;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsStocksApi
 */
@Ignore
public class ProductsStocksApiTest {

    private final ProductsStocksApi api = new ProductsStocksApi();

    @Before
    public void init() throws ApiException {
        MerchantSignInRequest merchantSignInRequest = new MerchantSignInRequest()
        .email("USERNAME")
        .password("PASS");
ApiSignInResponse response = new UserApi().signInWithApi(merchantSignInRequest);
String apiToken = response.getApiToken();
        Configuration
        .getDefaultApiClient()
        .setReadTimeout(10000000)
        .setBasePath("http://localhost:8080/api-1.0-SNAPSHOT/v1")
        .setApiKey(apiToken);
    }
    
    /**
     * 
     *
     * Retrieves all products
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(timeout = 1000000000)
    public void findAllProductsTest() throws ApiException {
        List<Product> response = api.findAllProducts();

        
    }
    
    /**
     * 
     *
     * Find Stocks
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllStocksTest() throws ApiException {
        StockRequest stockRequest = new StockRequest();
        stockRequest.addTypesItem(TypesEnum.TEXT);

        stockRequest.addSkusItem("iTunes-10-USD");
        List<SimpleStockPojo> response = api.findAllStocks(stockRequest);
    }
 
}

