/*
 * Prepaidforge API
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.Configuration;
import org.openapitools.client.model.ApiSignInResponse;
import org.openapitools.client.model.MerchantSignInRequest;

import org.junit.Test;
import org.junit.runners.JUnit4;
import org.junit.Assert;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
public class UserApiTest {

    /**
     * 
     *
     * Sign in link for api users
     *
     * @throws ApiException if the Api call fails
     */
    @Test(timeout = 100000)
    public void signInWithApiTest() throws ApiException {
        Configuration.getDefaultApiClient().setBasePath("http://localhost:8080/api-1.0-SNAPSHOT/v1");
        MerchantSignInRequest merchantSignInRequest = new MerchantSignInRequest().email("USERNAME").password("PASS");
        ApiSignInResponse response = new UserApi().signInWithApi(merchantSignInRequest);
        String apiToken = response.getApiToken();
        String s = response.getTokenValidUntil();

        Assert.assertNotNull(apiToken);
        Assert.assertNotNull(s);
    }

}
